### ISSUE TITLE
Possible bug on ./run

### ISSUE THREAD

**Issue by panostzemis** [martmaiste/nginx-certbot#1]
Dear Mart,

When i installed your latest version I faced the logs bellow 👍 

docker logs nginx
grep: unrecognized option: quiet
BusyBox v1.27.2 (2018-06-06 09:08:44 UTC) multi-call binary.

Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

        -H      Add 'filename:' prefix
        -h      Do not add 'filename:' prefix
        -n      Add 'line_no:' prefix
        -l      Show only names of files that match
        -L      Show only names of files that don't match
        -c      Show only count of matching lines
        -o      Show only the matching part of line
        -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
        -v      Select non-matching lines
        -s      Suppress open and read errors
        -r      Recurse
        -i      Ignore case
        -w      Match whole words only
        -x      Match whole lines only
        -F      PATTERN is a literal (not regexp)
        -E      PATTERN is an extended regexp
        -m N    Match up to N times per file
        -A N    Print N lines of trailing context
        -B N    Print N lines of leading context
        -C N    Same as '-A N -B N'
        -e PTRN Pattern to match
        -f FILE Read pattern from file
grep: unrecognized option: quiet
BusyBox v1.27.2 (2018-06-06 09:08:44 UTC) multi-call binary.

Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

        -H      Add 'filename:' prefix
        -h      Do not add 'filename:' prefix
        -n      Add 'line_no:' prefix
        -l      Show only names of files that match
        -L      Show only names of files that don't match
        -c      Show only count of matching lines
        -o      Show only the matching part of line
        -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
        -v      Select non-matching lines
        -s      Suppress open and read errors
        -r      Recurse
        -i      Ignore case
        -w      Match whole words only
        -x      Match whole lines only
        -F      PATTERN is a literal (not regexp)
        -E      PATTERN is an extended regexp
        -m N    Match up to N times per file
        -A N    Print N lines of trailing context
        -B N    Print N lines of leading context
        -C N    Same as '-A N -B N'
        -e PTRN Pattern to match
        -f FILE Read pattern from file
Creating directories for certificates...
Generating self-signed certificates...

...

-----END CERTIFICATE-----
Updating permissions...
Permissions in /etc/nginx are correct.
Permissions in /var/log are correct.
Updating permissions in /var/lib/nginx...
Permissions in /tmp are correct.
Permissions in /etc/s6.d are correct.
Done updating permissions.
./run: line 5: syntax error: unexpected newline
./run: line 5: syntax error: unexpected newline
./run: line 5: syntax error: unexpected newline
./run: line 5: syntax error: unexpected newline
./run: line 5: syntax error: unexpected newline
./run: line 5: syntax error: unexpected newline
./run: line 5: syntax error: unexpected newline

and that last error goes on for ever. Could you possible know what's triggers it?

Kind Regards

**Comment by martmaiste** [comment]
Thanks Panos,
grep in run.sh script did not like --quiet but was happy with -q. Dockerhub image is now also updated.

**Comment by panostzemis** [comment]
Dear Mart,

Thank you for looking into it so rapidly.
I tested and everything works great.

Regards,
Panos
