### ISSUE TITLE
Upgrading to alpine 3.9

### ISSUE THREAD

**Issue by sergey-sobolev** [martmaiste/nginx-certbot#3]
Hi,
please consider upgrading to a newer version of alpine (e.g. 3.9) as with the version 3.7 certbot has crypto libraries version conflict (those installed with alpine 3.7 are too old).

For alpine 3.9 the Dockerfile needs the following changes:
<pre>
@@ -1,4 +1,4 @@
-FROM alpine:3.7
+FROM alpine:3.9
 
 ENV UID=0 GID=0 \
     UPLOAD_MAX_SIZE=10G \
@@ -10,7 +10,7 @@ RUN addgroup -S nginx \
  && adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
  && apk -U upgrade && apk add \
     bash \
-    libssl1.0 \
+    libssl1.1 \
     openssl \
     certbot \   
     nginx \
</pre>

**Comment by martmaiste** [comment]
Hi, alpine version and libssl1.1 are now updated in Dockerfile. I'm not sure whether the libssl1.1 is actually necessary with alpine 3.9 but I still left it in at the moment.

**Comment by sergey-sobolev** [comment]
thank you for the update!
